import type { Opening } from './types';

export const OPENINGS: Opening[] = [
  {
    id: 'abertura-italiana',
    name: { pt: 'Abertura Italiana', en: 'Italian Game' },
    description: {
      pt: 'Uma das aberturas mais antigas e diretas: o bispo branco mira logo a casa fraca f7, levando a posições ricas em ataque.',
      en: 'One of the oldest and most direct openings: the white bishop takes aim at the weak f7 square right away, leading to attack-rich positions.',
    },
    lines: [
      {
        name: { pt: 'Linha principal (Giuoco Piano)', en: 'Main line (Giuoco Piano)' },
        eco: 'C50',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro e abre linha para o bispo e a dama.', en: 'Occupies the center and opens a line for the bishop and queen.' } },
          { san: 'e5', explanation: { pt: 'Resposta simétrica: também disputa o centro imediatamente.', en: 'Symmetric response: also contests the center immediately.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve uma peça, ataca o peão e5 e prepara o roque.', en: 'Develops a piece, attacks the e5 pawn, and prepares to castle.' } },
          { san: 'Nc6', explanation: { pt: 'Defende o peão e5 e desenvolve uma peça em direção ao centro.', en: 'Defends the e5 pawn and develops a piece toward the center.' } },
          { san: 'Bc4', explanation: { pt: 'O bispo mira a casa fraca f7, o alvo clássico da Italiana.', en: 'The bishop aims at the weak f7 square, the classic target of the Italian.' } },
          { san: 'Bc5', explanation: { pt: 'Desenvolve o bispo para a mesma diagonal, espelhando a ideia branca.', en: "Develops the bishop to the same diagonal, mirroring White's idea." } },
          { san: 'c3', explanation: { pt: 'Prepara d4 para ganhar espaço no centro, apoiado por este peão.', en: 'Prepares d4 to gain central space, supported by this pawn.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve o último cavalo menor e ataca o peão e4.', en: 'Develops the last minor piece and attacks the e4 pawn.' } },
          { san: 'd3', explanation: { pt: 'Protege o peão e4 e mantém a estrutura sólida antes do roque.', en: 'Protects the e4 pawn and keeps the structure solid before castling.' } },
        ],
      },
      {
        name: { pt: 'Gambito Evans', en: 'Evans Gambit' },
        eco: 'C51',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro e abre linha para o bispo e a dama.', en: 'Occupies the center and opens a line for the bishop and queen.' } },
          { san: 'e5', explanation: { pt: 'Resposta simétrica: também disputa o centro imediatamente.', en: 'Symmetric response: also contests the center immediately.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve uma peça, ataca o peão e5 e prepara o roque.', en: 'Develops a piece, attacks the e5 pawn, and prepares to castle.' } },
          { san: 'Nc6', explanation: { pt: 'Defende o peão e5 e desenvolve uma peça em direção ao centro.', en: 'Defends the e5 pawn and develops a piece toward the center.' } },
          { san: 'Bc4', explanation: { pt: 'O bispo mira a casa fraca f7, o alvo clássico da Italiana.', en: 'The bishop aims at the weak f7 square, the classic target of the Italian.' } },
          { san: 'Bc5', explanation: { pt: 'Desenvolve o bispo para a mesma diagonal, espelhando a ideia branca.', en: "Develops the bishop to the same diagonal, mirroring White's idea." } },
          { san: 'b4', explanation: { pt: 'O Gambito Evans: sacrifica um peão para ganhar tempo e um centro forte.', en: 'The Evans Gambit: sacrifices a pawn to gain time and a strong center.' } },
          { san: 'Bxb4', explanation: { pt: 'Aceita o peão oferecido — recusar também é possível, mas capturar é a linha principal.', en: 'Accepts the offered pawn — declining is also possible, but capturing is the main line.' } },
          { san: 'c3', explanation: { pt: 'Ataca o bispo e prepara d4, construindo um grande centro de peões em troca do material sacrificado.', en: 'Attacks the bishop and prepares d4, building a big pawn center in exchange for the sacrificed material.' } },
        ],
      },
    ],
  },
  {
    id: 'abertura-espanhola',
    name: { pt: 'Abertura Espanhola', en: 'Ruy Lopez' },
    description: {
      pt: 'A abertura mais jogada da história ao mais alto nível: o bispo pressiona o cavalo que defende o peão e5, para uma luta longa e rica.',
      en: 'The most-played opening in history at the highest level: the bishop pressures the knight defending the e5 pawn, leading to a long and rich struggle.',
    },
    lines: [
      {
        name: { pt: 'Linha principal (Variante Fechada)', en: 'Main line (Closed Variation)' },
        eco: 'C84',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'e5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve e ataca o peão e5.', en: 'Develops and attacks the e5 pawn.' } },
          { san: 'Nc6', explanation: { pt: 'Defende o peão e5.', en: 'Defends the e5 pawn.' } },
          { san: 'Bb5', explanation: { pt: 'A Espanhola: o bispo pressiona o cavalo que defende e5.', en: 'The Ruy Lopez: the bishop pressures the knight defending e5.' } },
          { san: 'a6', explanation: { pt: 'Pergunta ao bispo: obriga-o a decidir-se (recuar, trocar ou avançar).', en: 'Questions the bishop: forces it to make a decision (retreat, trade, or advance).' } },
          { san: 'Ba4', explanation: { pt: 'Mantém a pressão sobre o cavalo, mirando indiretamente o peão e5.', en: 'Keeps the pressure on the knight, indirectly aiming at the e5 pawn.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve o último cavalo menor e contra-ataca o peão e4.', en: 'Develops the last minor piece and counterattacks the e4 pawn.' } },
          { san: 'O-O', explanation: { pt: 'Roca, colocando o rei em segurança antes de continuar o plano central.', en: 'Castles, tucking the king to safety before continuing the central plan.' } },
          { san: 'Be7', explanation: { pt: 'Desenvolve o bispo e prepara o próprio roque.', en: 'Develops the bishop and prepares to castle.' } },
          { san: 'Re1', explanation: { pt: 'Reforça o peão e4 pela coluna, preparando um futuro d4.', en: 'Reinforces the e4 pawn along the file, preparing a future d4.' } },
        ],
      },
      {
        name: { pt: 'Variante Berlinense', en: 'Berlin Variation' },
        eco: 'C65',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'e5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve e ataca o peão e5.', en: 'Develops and attacks the e5 pawn.' } },
          { san: 'Nc6', explanation: { pt: 'Defende o peão e5.', en: 'Defends the e5 pawn.' } },
          { san: 'Bb5', explanation: { pt: 'A Espanhola: pressiona o cavalo que defende e5.', en: 'The Ruy Lopez: pressures the knight defending e5.' } },
          { san: 'Nf6', explanation: { pt: 'A Defesa Berlinense: contra-ataca o peão e4 em vez de responder a6.', en: 'The Berlin Defense: counterattacks the e4 pawn instead of playing a6.' } },
          { san: 'O-O', explanation: { pt: 'Ignora a ameaça momentânea a e4: as pretas vão capturar este peão já a seguir, mas as brancas recuperam-no pouco depois com d4 e Re1.', en: "Ignores the momentary threat to e4: Black is about to capture this pawn, but White recovers it shortly after with d4 and Re1." } },
          { san: 'Nxe4', explanation: { pt: 'As pretas capturam o peão e4, a linha principal da Berlinense.', en: 'Black captures the e4 pawn, the main line of the Berlin.' } },
          { san: 'd4', explanation: { pt: 'Abre o centro para explorar o cavalo avançado e preparar a recuperação do material.', en: 'Opens the center to exploit the advanced knight and prepare to recover the material.' } },
          { san: 'Nd6', explanation: { pt: 'O cavalo recua, atacando o bispo em b5 e preparando um final de peças característico desta variante.', en: "The knight retreats, attacking the bishop on b5 and heading toward the pawn endgame characteristic of this variation." } },
        ],
      },
    ],
  },
  {
    id: 'defesa-siciliana',
    name: { pt: 'Defesa Siciliana', en: 'Sicilian Defense' },
    description: {
      pt: 'A resposta mais popular e agressiva a 1.e4: as pretas contra-atacam assimetricamente, gerando posições muito ricas para os dois lados.',
      en: 'The most popular and aggressive response to 1.e4: Black counterattacks asymmetrically, generating very rich positions for both sides.',
    },
    lines: [
      {
        name: { pt: 'Linha principal (Aberta)', en: 'Main line (Open)' },
        eco: 'B50',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'c5', explanation: { pt: 'A Siciliana: pretas contra-atacam assimetricamente em vez de responder e5.', en: 'The Sicilian: Black counterattacks asymmetrically instead of playing e5.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve e prepara d4 para abrir o centro.', en: 'Develops and prepares d4 to open the center.' } },
          { san: 'd6', explanation: { pt: 'Prepara o desenvolvimento do cavalo para f6 sem o expor a um avanço do peão e.', en: 'Prepares to develop the knight to f6 without exposing it to an e-pawn advance.' } },
          { san: 'd4', explanation: { pt: 'Abre o centro, oferecendo a troca de peões.', en: 'Opens the center, offering the pawn trade.' } },
          { san: 'cxd4', explanation: { pt: 'Captura, aceitando a troca central.', en: 'Captures, accepting the central trade.' } },
          { san: 'Nxd4', explanation: { pt: 'O cavalo recaptura, centralizando-se e mantendo o controlo do centro.', en: 'The knight recaptures, centralizing itself and keeping control of the center.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve o cavalo, atacando o peão e4.', en: 'Develops the knight, attacking the e4 pawn.' } },
          { san: 'Nc3', explanation: { pt: 'Defende o peão e4 e desenvolve mais uma peça.', en: 'Defends the e4 pawn and develops another piece.' } },
        ],
      },
      {
        name: { pt: 'Najdorf', en: 'Najdorf' },
        eco: 'B90',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'c5', explanation: { pt: 'A Siciliana: pretas contra-atacam assimetricamente em vez de responder e5.', en: 'The Sicilian: Black counterattacks asymmetrically instead of playing e5.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve e prepara d4 para abrir o centro.', en: 'Develops and prepares d4 to open the center.' } },
          { san: 'd6', explanation: { pt: 'Prepara o desenvolvimento do cavalo para f6 sem o expor a um avanço do peão e.', en: 'Prepares to develop the knight to f6 without exposing it to an e-pawn advance.' } },
          { san: 'd4', explanation: { pt: 'Abre o centro, oferecendo a troca de peões.', en: 'Opens the center, offering the pawn trade.' } },
          { san: 'cxd4', explanation: { pt: 'Captura, aceitando a troca central.', en: 'Captures, accepting the central trade.' } },
          { san: 'Nxd4', explanation: { pt: 'O cavalo recaptura, centralizando-se e mantendo o controlo do centro.', en: 'The knight recaptures, centralizing itself and keeping control of the center.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve o cavalo, atacando o peão e4.', en: 'Develops the knight, attacking the e4 pawn.' } },
          { san: 'Nc3', explanation: { pt: 'Defende o peão e4 e desenvolve mais uma peça.', en: 'Defends the e4 pawn and develops another piece.' } },
          { san: 'a6', explanation: { pt: 'A Najdorf: impede Bb5+/Nb5 e mantém flexibilidade total para o desenvolvimento seguinte (...e5, ...b5, etc.).', en: 'The Najdorf: prevents Bb5+/Nb5 and keeps total flexibility for the following development (...e5, ...b5, etc.).' } },
        ],
      },
      {
        name: { pt: 'Dragão', en: 'Dragon' },
        eco: 'B70',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'c5', explanation: { pt: 'A Siciliana: pretas contra-atacam assimetricamente em vez de responder e5.', en: 'The Sicilian: Black counterattacks asymmetrically instead of playing e5.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve e prepara d4 para abrir o centro.', en: 'Develops and prepares d4 to open the center.' } },
          { san: 'd6', explanation: { pt: 'Prepara o desenvolvimento do cavalo para f6 sem o expor a um avanço do peão e.', en: 'Prepares to develop the knight to f6 without exposing it to an e-pawn advance.' } },
          { san: 'd4', explanation: { pt: 'Abre o centro, oferecendo a troca de peões.', en: 'Opens the center, offering the pawn trade.' } },
          { san: 'cxd4', explanation: { pt: 'Captura, aceitando a troca central.', en: 'Captures, accepting the central trade.' } },
          { san: 'Nxd4', explanation: { pt: 'O cavalo recaptura, centralizando-se e mantendo o controlo do centro.', en: 'The knight recaptures, centralizing itself and keeping control of the center.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve o cavalo, atacando o peão e4.', en: 'Develops the knight, attacking the e4 pawn.' } },
          { san: 'Nc3', explanation: { pt: 'Defende o peão e4 e desenvolve mais uma peça.', en: 'Defends the e4 pawn and develops another piece.' } },
          { san: 'g6', explanation: { pt: 'O Dragão: prepara Bg7, fianchettando o bispo para uma diagonal poderosa apontada ao centro e ao flanco de dama branco.', en: 'The Dragon: prepares Bg7, fianchettoing the bishop onto a powerful diagonal aimed at the center and the white queenside.' } },
        ],
      },
    ],
  },
  {
    id: 'defesa-francesa',
    name: { pt: 'Defesa Francesa', en: 'French Defense' },
    description: {
      pt: 'Uma defesa sólida contra 1.e4, onde as pretas aceitam um bispo temporariamente fechado em troca de uma estrutura de peões robusta.',
      en: 'A solid defense against 1.e4, where Black accepts a temporarily closed-in bishop in exchange for a robust pawn structure.',
    },
    lines: [
      {
        name: { pt: 'Linha principal (Variante de Troca)', en: 'Main line (Exchange Variation)' },
        eco: 'C01',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'e6', explanation: { pt: 'A Francesa: prepara ...d5 sustentando o contra-ataque central antes de desenvolver o bispo de casas claras.', en: 'The French: prepares ...d5, backing up the central counterattack before developing the light-squared bishop.' } },
          { san: 'd4', explanation: { pt: 'Reforça o centro.', en: 'Reinforces the center.' } },
          { san: 'd5', explanation: { pt: 'Desafia diretamente o peão e4.', en: 'Directly challenges the e4 pawn.' } },
          { san: 'exd5', explanation: { pt: 'Variante de Troca: simplifica o centro em vez de manter a tensão.', en: 'Exchange Variation: simplifies the center instead of keeping the tension.' } },
          { san: 'exd5', explanation: { pt: 'Recaptura, chegando a uma posição simétrica e mais tranquila.', en: 'Recaptures, reaching a symmetric and calmer position.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve, controlando o centro.', en: 'Develops, controlling the center.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve simetricamente.', en: 'Develops symmetrically.' } },
          { san: 'Bd3', explanation: { pt: 'Desenvolve o bispo para uma diagonal ativa, visando o flanco do rei.', en: 'Develops the bishop to an active diagonal, aiming at the kingside.' } },
        ],
      },
      {
        name: { pt: 'Variante do Avanço', en: 'Advance Variation' },
        eco: 'C02',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'e6', explanation: { pt: 'A Francesa: prepara ...d5.', en: 'The French: prepares ...d5.' } },
          { san: 'd4', explanation: { pt: 'Reforça o centro.', en: 'Reinforces the center.' } },
          { san: 'd5', explanation: { pt: 'Desafia o peão e4.', en: 'Challenges the e4 pawn.' } },
          { san: 'e5', explanation: { pt: 'Variante do Avanço: ganha espaço, fechando o centro e trancando o bispo de casas claras das pretas.', en: "Advance Variation: gains space, closing the center and locking in Black's light-squared bishop." } },
          { san: 'c5', explanation: { pt: 'Contra-ataca imediatamente a base da cadeia de peões brancos, o plano típico contra o Avanço.', en: "Immediately counterattacks the base of White's pawn chain, the typical plan against the Advance." } },
          { san: 'c3', explanation: { pt: 'Defende o peão d4, mantendo a cadeia central intacta.', en: 'Defends the d4 pawn, keeping the central chain intact.' } },
          { san: 'Nc6', explanation: { pt: 'Desenvolve, pressionando ainda mais o peão d4.', en: 'Develops, pressuring the d4 pawn further.' } },
          { san: 'Nf3', explanation: { pt: 'Defende o peão d4 mais uma vez antes de continuar o desenvolvimento.', en: 'Defends the d4 pawn once more before continuing development.' } },
        ],
      },
    ],
  },
  {
    id: 'defesa-caro-kann',
    name: { pt: 'Defesa Caro-Kann', en: 'Caro-Kann Defense' },
    description: {
      pt: 'Como a Francesa, mas com o bispo de casas claras livre desde o início — uma escolha sólida e pouco arriscada contra 1.e4.',
      en: "Like the French, but with the light-squared bishop free from the start — a solid, low-risk choice against 1.e4.",
    },
    lines: [
      {
        name: { pt: 'Linha principal (Variante do Avanço)', en: 'Main line (Advance Variation)' },
        eco: 'B12',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'c6', explanation: { pt: 'A Caro-Kann: prepara ...d5.', en: 'The Caro-Kann: prepares ...d5.' } },
          { san: 'd4', explanation: { pt: 'Reforça o centro.', en: 'Reinforces the center.' } },
          { san: 'd5', explanation: { pt: 'Desafia o peão e4.', en: 'Challenges the e4 pawn.' } },
          { san: 'e5', explanation: { pt: 'Variante do Avanço: ganha espaço fechando o centro.', en: 'Advance Variation: gains space by closing the center.' } },
          { san: 'Bf5', explanation: { pt: 'Desenvolve o bispo de casas claras antes de o fechar com ...e6 — a vantagem estrutural clássica da Caro-Kann face à Francesa.', en: "Develops the light-squared bishop before closing it in with ...e6 — the classic structural advantage of the Caro-Kann over the French." } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve e reforça d4; se ...Bg4 fixar o cavalo, Be2 quebra a prisão a seguir.', en: 'Develops and reinforces d4; if ...Bg4 pins the knight, Be2 breaks the pin next.' } },
          { san: 'e6', explanation: { pt: 'Abre espaço para o outro bispo e prepara o desenvolvimento do cavalo em direção ao centro.', en: 'Opens space for the other bishop and prepares to develop the knight toward the center.' } },
          { san: 'Be2', explanation: { pt: 'Desenvolve com solidez, preparando o roque.', en: 'Develops solidly, preparing to castle.' } },
          { san: 'c5', explanation: { pt: 'Contra-ataca a base da cadeia de peões brancos, tal como na Francesa.', en: "Counterattacks the base of White's pawn chain, just like in the French." } },
        ],
      },
      {
        name: { pt: 'Variante Clássica', en: 'Classical Variation' },
        eco: 'B18',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'c6', explanation: { pt: 'A Caro-Kann: prepara ...d5.', en: 'The Caro-Kann: prepares ...d5.' } },
          { san: 'd4', explanation: { pt: 'Reforça o centro.', en: 'Reinforces the center.' } },
          { san: 'd5', explanation: { pt: 'Desafia o peão e4.', en: 'Challenges the e4 pawn.' } },
          { san: 'Nc3', explanation: { pt: 'Defende o peão e4 desenvolvendo uma peça.', en: 'Defends the e4 pawn while developing a piece.' } },
          { san: 'dxe4', explanation: { pt: 'Captura o peão central, aceitando a troca.', en: 'Captures the central pawn, accepting the trade.' } },
          { san: 'Nxe4', explanation: { pt: 'Recaptura, deixando o cavalo centralizado mas atacável.', en: 'Recaptures, leaving the knight centralized but attackable.' } },
          { san: 'Bf5', explanation: { pt: 'Desenvolve o bispo antes de fechar-lhe a saída com ...e6, a ideia-chave da Caro-Kann.', en: "Develops the bishop before closing its escape route with ...e6, the key idea of the Caro-Kann." } },
          { san: 'Ng3', explanation: { pt: 'Ataca o bispo, ganhando tempo.', en: 'Attacks the bishop, gaining a tempo.' } },
          { san: 'Bg6', explanation: { pt: 'Recua mantendo o bispo ativo fora da cadeia de peões.', en: 'Retreats, keeping the bishop active outside the pawn chain.' } },
        ],
      },
    ],
  },
  {
    id: 'gambito-da-dama',
    name: { pt: 'Gambito da Dama', en: "Queen's Gambit" },
    description: {
      pt: 'A abertura clássica de 1.d4: as brancas oferecem um peão lateral para ganhar espaço e tempo no centro.',
      en: "The classic 1.d4 opening: White offers a wing pawn to gain space and time in the center.",
    },
    lines: [
      {
        name: { pt: 'Aceite', en: 'Accepted' },
        eco: 'D20',
        moves: [
          { san: 'd4', explanation: { pt: 'Ocupa o centro pelo lado da dama.', en: 'Occupies the center on the queenside.' } },
          { san: 'd5', explanation: { pt: 'Resposta simétrica, disputando o centro.', en: 'Symmetric response, contesting the center.' } },
          { san: 'c4', explanation: { pt: 'O Gambito da Dama: oferece este peão para desviar o peão d5 e ganhar mais espaço central.', en: "The Queen's Gambit: offers this pawn to divert the d5 pawn and gain more central space." } },
          { san: 'dxc4', explanation: { pt: 'Aceita o gambito, capturando o peão oferecido.', en: 'Accepts the gambit, capturing the offered pawn.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve antes de recuperar o peão, evitando perder tempo.', en: 'Develops before recovering the pawn, avoiding a loss of time.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve simetricamente.', en: 'Develops symmetrically.' } },
          { san: 'e3', explanation: { pt: 'Prepara Bxc4, recuperando o peão em breve.', en: 'Prepares Bxc4, recovering the pawn shortly.' } },
          { san: 'e6', explanation: { pt: 'Desenvolve espaço para o bispo de casas claras e prepara o próprio desenvolvimento.', en: "Opens space for the light-squared bishop and prepares its own development." } },
          { san: 'Bxc4', explanation: { pt: 'Recupera o peão sacrificado, com uma posição de desenvolvimento natural e boa.', en: 'Recovers the sacrificed pawn, with a naturally good developing position.' } },
        ],
      },
      {
        name: { pt: 'Recusado', en: 'Declined' },
        eco: 'D30',
        moves: [
          { san: 'd4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'd5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'c4', explanation: { pt: 'Oferece o peão do gambito.', en: 'Offers the gambit pawn.' } },
          { san: 'e6', explanation: { pt: 'Recusa capturar: reforça o centro em vez de ganhar o peão, a ideia da Defesa Recusada.', en: "Declines to capture: reinforces the center instead of grabbing the pawn, the idea of the Queen's Gambit Declined." } },
          { san: 'Nc3', explanation: { pt: 'Desenvolve, mantendo a pressão sobre d5.', en: 'Develops, keeping the pressure on d5.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve, defendendo indiretamente d5.', en: 'Develops, indirectly defending d5.' } },
          { san: 'Bg5', explanation: { pt: 'Prende o cavalo à dama, uma pressão típica desta variante.', en: 'Pins the knight to the queen, a typical pressure in this variation.' } },
          { san: 'Be7', explanation: { pt: 'Desenvolve o bispo e prepara quebrar a prisão com ...Ne4 ou apenas continuar o roque.', en: 'Develops the bishop and prepares to break the pin with ...Ne4, or simply continue toward castling.' } },
          { san: 'e3', explanation: { pt: 'Reforça o centro e abre a diagonal para o bispo de casas claras.', en: 'Reinforces the center and opens the diagonal for the light-squared bishop.' } },
        ],
      },
    ],
  },
  {
    id: 'defesa-eslava',
    name: { pt: 'Defesa Eslava', en: 'Slav Defense' },
    description: {
      pt: 'Uma resposta sólida ao Gambito da Dama, que reforça o centro sem fechar o bispo de casas claras.',
      en: "A solid response to the Queen's Gambit that reinforces the center without shutting in the light-squared bishop.",
    },
    lines: [
      {
        name: { pt: 'Linha principal', en: 'Main line' },
        eco: 'D10',
        moves: [
          { san: 'd4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'd5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'c4', explanation: { pt: 'Oferece o peão do gambito.', en: 'Offers the gambit pawn.' } },
          { san: 'c6', explanation: { pt: 'A Defesa Eslava: reforça d5 com este peão, mantendo o bispo de casas claras livre (ao contrário da Recusada).', en: "The Slav Defense: reinforces d5 with this pawn, keeping the light-squared bishop free (unlike the Declined)." } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve.', en: 'Develops.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve simetricamente.', en: 'Develops symmetrically.' } },
          { san: 'Nc3', explanation: { pt: 'Desenvolve, mantendo a pressão central.', en: 'Develops, keeping the central pressure.' } },
          { san: 'dxc4', explanation: { pt: 'Captura o peão do gambito, um plano típico da Eslava.', en: 'Captures the gambit pawn, a typical Slav plan.' } },
          { san: 'a4', explanation: { pt: 'Impede ...b5, que defenderia o peão extra, preparando a sua recuperação.', en: 'Prevents ...b5, which would defend the extra pawn, preparing to recover it.' } },
        ],
      },
      {
        name: { pt: 'Semi-Eslava', en: 'Semi-Slav' },
        eco: 'D43',
        moves: [
          { san: 'd4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'd5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'c4', explanation: { pt: 'Oferece o peão do gambito.', en: 'Offers the gambit pawn.' } },
          { san: 'c6', explanation: { pt: 'A Defesa Eslava: reforça d5.', en: 'The Slav Defense: reinforces d5.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve.', en: 'Develops.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve simetricamente.', en: 'Develops symmetrically.' } },
          { san: 'Nc3', explanation: { pt: 'Desenvolve, mantendo a pressão central.', en: 'Develops, keeping the central pressure.' } },
          { san: 'e6', explanation: { pt: 'A Semi-Eslava: acrescenta este peão, combinando as ideias da Eslava com as da Recusada, ao custo de fechar temporariamente o bispo de casas claras.', en: "The Semi-Slav: adds this pawn, combining the ideas of the Slav with those of the Declined, at the cost of temporarily shutting in the light-squared bishop." } },
          { san: 'Bg5', explanation: { pt: 'Prende o cavalo à dama, tal como na Recusada, aproveitando que o bispo eslavo ainda não saiu.', en: "Pins the knight to the queen, just like in the Declined, taking advantage of the fact that the Slav bishop hasn't come out yet." } },
        ],
      },
    ],
  },
  {
    id: 'abertura-inglesa',
    name: { pt: 'Abertura Inglesa', en: 'English Opening' },
    description: {
      pt: 'Uma abertura flexível pelo flanco de dama, que pode transpor para muitas estruturas diferentes.',
      en: 'A flexible queenside opening that can transpose into many different structures.',
    },
    lines: [
      {
        name: { pt: 'Linha principal (Simétrica)', en: 'Main line (Symmetrical)' },
        eco: 'A30',
        moves: [
          { san: 'c4', explanation: { pt: 'A Inglesa: ocupa o centro pelo flanco, deixando mais opções de estrutura de peões em aberto.', en: 'The English: occupies the center from the flank, leaving more pawn-structure options open.' } },
          { san: 'c5', explanation: { pt: 'Resposta simétrica, espelhando o plano branco.', en: "Symmetric response, mirroring White's plan." } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve, controlando o centro à distância.', en: 'Develops, controlling the center from a distance.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve simetricamente.', en: 'Develops symmetrically.' } },
          { san: 'g3', explanation: { pt: 'Prepara o fianchetto do bispo, um plano típico da Inglesa.', en: 'Prepares to fianchetto the bishop, a typical English plan.' } },
          { san: 'b6', explanation: { pt: 'Espelha o plano com o próprio fianchetto.', en: 'Mirrors the plan with its own fianchetto.' } },
          { san: 'Bg2', explanation: { pt: 'Completa o fianchetto, pressionando a diagonal longa.', en: 'Completes the fianchetto, pressuring the long diagonal.' } },
          { san: 'Bb7', explanation: { pt: 'Completa o fianchetto simétrico.', en: 'Completes the symmetric fianchetto.' } },
          { san: 'O-O', explanation: { pt: 'Roca, colocando o rei em segurança numa posição ainda muito flexível.', en: 'Castles, tucking the king to safety in a position that is still very flexible.' } },
        ],
      },
      {
        name: { pt: 'Quatro Cavalos', en: 'Four Knights' },
        eco: 'A29',
        moves: [
          { san: 'c4', explanation: { pt: 'A Inglesa: ocupa o centro pelo flanco.', en: 'The English: occupies the center from the flank.' } },
          { san: 'c5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve.', en: 'Develops.' } },
          { san: 'Nc6', explanation: { pt: 'Desenvolve, controlando o centro.', en: 'Develops, controlling the center.' } },
          { san: 'Nc3', explanation: { pt: 'Desenvolve simetricamente, a linha dos Quatro Cavalos.', en: 'Develops symmetrically, the Four Knights line.' } },
          { san: 'Nf6', explanation: { pt: 'Completa o desenvolvimento dos quatro cavalos.', en: 'Completes the development of all four knights.' } },
          { san: 'g3', explanation: { pt: 'Prepara o fianchetto do bispo.', en: 'Prepares to fianchetto the bishop.' } },
          { san: 'd5', explanation: { pt: 'Rompe no centro antes que as brancas completem o fianchetto, a ideia principal desta variante.', en: 'Breaks in the center before White completes the fianchetto, the main idea of this variation.' } },
          { san: 'cxd5', explanation: { pt: 'Captura, aceitando entrar numa posição mais aberta e tática.', en: 'Captures, agreeing to enter a more open, tactical position.' } },
        ],
      },
    ],
  },
  {
    id: 'defesa-pirc',
    name: { pt: 'Defesa Pirc', en: 'Pirc Defense' },
    description: {
      pt: 'Uma defesa hipermoderna contra 1.e4: as pretas deixam as brancas ocupar o centro, para o atacar depois com peças desenvolvidas em fianchetto.',
      en: 'A hypermodern defense against 1.e4: Black lets White occupy the center, planning to attack it later with fianchettoed pieces.',
    },
    lines: [
      {
        name: { pt: 'Linha principal (Ataque Austríaco)', en: 'Main line (Austrian Attack)' },
        eco: 'B09',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'd6', explanation: { pt: 'A Pirc: adia o contacto central, preparando o fianchetto do bispo em vez de responder ...e5 ou ...c5.', en: 'The Pirc: delays central contact, preparing to fianchetto the bishop instead of playing ...e5 or ...c5.' } },
          { san: 'd4', explanation: { pt: 'Reforça o centro.', en: 'Reinforces the center.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve, atacando o peão e4.', en: 'Develops, attacking the e4 pawn.' } },
          { san: 'Nc3', explanation: { pt: 'Defende o peão e4.', en: 'Defends the e4 pawn.' } },
          { san: 'g6', explanation: { pt: 'Prepara o fianchetto do bispo, o plano central da Pirc.', en: "Prepares to fianchetto the bishop, the Pirc's central plan." } },
          { san: 'f4', explanation: { pt: 'Ataque Austríaco: constrói um grande centro de peões e prepara um ataque agressivo no flanco do rei.', en: 'Austrian Attack: builds a big pawn center and prepares an aggressive kingside attack.' } },
          { san: 'Bg7', explanation: { pt: 'Completa o fianchetto, pressionando o centro alargado das brancas.', en: "Completes the fianchetto, pressuring White's extended center." } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve, reforçando o centro antes de continuar o plano de ataque.', en: 'Develops, reinforcing the center before continuing the attacking plan.' } },
        ],
      },
      {
        name: { pt: 'Variante Clássica', en: 'Classical Variation' },
        eco: 'B08',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'd6', explanation: { pt: 'A Pirc: adia o contacto central, preparando o fianchetto do bispo.', en: 'The Pirc: delays central contact, preparing to fianchetto the bishop.' } },
          { san: 'd4', explanation: { pt: 'Reforça o centro.', en: 'Reinforces the center.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve, atacando o peão e4.', en: 'Develops, attacking the e4 pawn.' } },
          { san: 'Nc3', explanation: { pt: 'Defende o peão e4.', en: 'Defends the e4 pawn.' } },
          { san: 'g6', explanation: { pt: 'Prepara o fianchetto do bispo.', en: 'Prepares to fianchetto the bishop.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve com solidez, em vez de avançar já o peão f.', en: 'Develops solidly, instead of pushing the f-pawn right away.' } },
          { san: 'Bg7', explanation: { pt: 'Completa o fianchetto.', en: 'Completes the fianchetto.' } },
          { san: 'Be2', explanation: { pt: 'Desenvolve o bispo de forma modesta, mas sólida, preparando o roque.', en: 'Develops the bishop modestly but solidly, preparing to castle.' } },
          { san: 'O-O', explanation: { pt: 'Roca, completando o desenvolvimento inicial em segurança.', en: 'Castles, safely completing the initial development.' } },
        ],
      },
    ],
  },
  {
    id: 'abertura-escocesa',
    name: { pt: 'Abertura Escocesa', en: 'Scotch Game' },
    description: {
      pt: 'Uma alternativa direta à Espanhola: as brancas abrem o centro já no terceiro lance.',
      en: 'A direct alternative to the Ruy Lopez: White opens the center as early as the third move.',
    },
    lines: [
      {
        name: { pt: 'Linha principal', en: 'Main line' },
        eco: 'C44',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'e5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve, atacando o peão e5.', en: 'Develops, attacking the e5 pawn.' } },
          { san: 'Nc6', explanation: { pt: 'Defende o peão e5.', en: 'Defends the e5 pawn.' } },
          { san: 'd4', explanation: { pt: 'A Escocesa: abre o centro imediatamente em vez de desenvolver o bispo primeiro.', en: 'The Scotch: opens the center immediately instead of developing the bishop first.' } },
          { san: 'exd4', explanation: { pt: 'Captura, aceitando a troca central.', en: 'Captures, accepting the central trade.' } },
          { san: 'Nxd4', explanation: { pt: 'Recaptura, centralizando o cavalo.', en: 'Recaptures, centralizing the knight.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve, atacando o peão e4.', en: 'Develops, attacking the e4 pawn.' } },
          { san: 'Nc3', explanation: { pt: 'Defende o peão e4, desenvolvendo mais uma peça.', en: 'Defends the e4 pawn while developing another piece.' } },
        ],
      },
      {
        name: { pt: 'Gambito Göring', en: 'Göring Gambit' },
        eco: 'C44',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'e5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve, atacando o peão e5.', en: 'Develops, attacking the e5 pawn.' } },
          { san: 'Nc6', explanation: { pt: 'Defende o peão e5.', en: 'Defends the e5 pawn.' } },
          { san: 'd4', explanation: { pt: 'A Escocesa: abre o centro imediatamente.', en: 'The Scotch: opens the center immediately.' } },
          { san: 'exd4', explanation: { pt: 'Captura, aceitando a troca central.', en: 'Captures, accepting the central trade.' } },
          { san: 'c3', explanation: { pt: 'O Gambito Göring: oferece mais um peão para acelerar o desenvolvimento e abrir linhas.', en: 'The Göring Gambit: offers another pawn to speed up development and open lines.' } },
          { san: 'dxc3', explanation: { pt: 'Aceita o segundo peão oferecido.', en: 'Accepts the second offered pawn.' } },
          { san: 'Nxc3', explanation: { pt: 'Recaptura, com um grande avanço de desenvolvimento em troca dos peões sacrificados.', en: 'Recaptures, with a big development lead in exchange for the sacrificed pawns.' } },
        ],
      },
    ],
  },
  {
    id: 'defesa-escandinava',
    name: { pt: 'Defesa Escandinava', en: 'Scandinavian Defense' },
    description: {
      pt: 'Uma resposta direta e pouco convencional a 1.e4: as pretas desafiam o peão central logo no primeiro lance.',
      en: 'A direct and unconventional response to 1.e4: Black challenges the central pawn right on the first move.',
    },
    lines: [
      {
        name: { pt: 'Linha principal (2...Qxd5)', en: 'Main line (2...Qxd5)' },
        eco: 'B01',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'd5', explanation: { pt: 'A Escandinava: desafia o peão e4 imediatamente, no primeiro lance.', en: 'The Scandinavian: challenges the e4 pawn immediately, on the very first move.' } },
          { san: 'exd5', explanation: { pt: 'Captura o peão oferecido.', en: 'Captures the offered pawn.' } },
          { san: 'Qxd5', explanation: { pt: 'Recaptura com a dama — pouco convencional tão cedo, mas direto.', en: 'Recaptures with the queen — unconventional this early, but direct.' } },
          { san: 'Nc3', explanation: { pt: 'Ataca a dama, ganhando tempo de desenvolvimento.', en: 'Attacks the queen, gaining a developing tempo.' } },
          { san: 'Qa5', explanation: { pt: 'Recua para uma casa ativa, mantendo pressão sobre e5 e a diagonal para o rei branco.', en: "Retreats to an active square, keeping pressure on e5 and the diagonal toward the white king." } },
          { san: 'd4', explanation: { pt: 'Reforça o centro, aproveitando o tempo ganho.', en: 'Reinforces the center, making use of the gained tempo.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve mais uma peça, seguindo o plano natural de acabar a mobilização antes de rocar.', en: 'Develops another piece, following the natural plan of finishing mobilization before castling.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve, protegendo o peão d4 e preparando o roque.', en: 'Develops, protecting the d4 pawn and preparing to castle.' } },
        ],
      },
      {
        name: { pt: 'Variante Moderna (2...Nf6)', en: 'Modern Variation (2...Nf6)' },
        eco: 'B01',
        moves: [
          { san: 'e4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'd5', explanation: { pt: 'A Escandinava: desafia o peão e4 imediatamente.', en: 'The Scandinavian: challenges the e4 pawn immediately.' } },
          { san: 'exd5', explanation: { pt: 'Captura o peão oferecido.', en: 'Captures the offered pawn.' } },
          { san: 'Nf6', explanation: { pt: 'Variante Moderna: em vez de recapturar já com a dama, desenvolve primeiro este cavalo, que vai recuperar o peão a seguir.', en: "Modern Variation: instead of recapturing with the queen right away, develops this knight first, which will recover the pawn next." } },
          { san: 'd4', explanation: { pt: 'Reforça o centro, defendendo o peão extra por agora.', en: 'Reinforces the center, defending the extra pawn for now.' } },
          { san: 'Nxd5', explanation: { pt: 'Recupera o peão com o cavalo, evitando expor a dama cedo demais.', en: "Recovers the pawn with the knight, avoiding exposing the queen too early." } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve, protegendo o centro.', en: 'Develops, protecting the center.' } },
          { san: 'Bg4', explanation: { pt: 'Desenvolve o bispo antes de lhe fechar a saída, prendendo o cavalo à dama.', en: 'Develops the bishop before its escape route closes, pinning the knight to the queen.' } },
          { san: 'Be2', explanation: { pt: 'Desenvolve com solidez, preparando quebrar a prisão com o roque e h3 mais tarde.', en: 'Develops solidly, preparing to break the pin with castling and h3 later.' } },
        ],
      },
    ],
  },
  {
    id: 'sistema-londres',
    name: { pt: 'Sistema Londres', en: 'London System' },
    description: {
      pt: 'Uma configuração sólida e fácil de aprender para as brancas, jogável com praticamente a mesma ideia contra quase qualquer resposta preta.',
      en: "A solid, easy-to-learn setup for White, playable with virtually the same idea against almost any Black response.",
    },
    lines: [
      {
        name: { pt: 'Linha principal', en: 'Main line' },
        eco: 'D02',
        moves: [
          { san: 'd4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'd5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve, controlando o centro.', en: 'Develops, controlling the center.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve simetricamente.', en: 'Develops symmetrically.' } },
          { san: 'Bf4', explanation: { pt: 'O Sistema Londres: desenvolve o bispo antes de lhe fechar a saída com e3, uma configuração sólida jogável contra quase qualquer resposta preta.', en: 'The London System: develops the bishop before closing its escape route with e3, a solid setup playable against almost any Black response.' } },
          { san: 'e6', explanation: { pt: 'Desenvolve espaço para o outro bispo.', en: 'Opens space for the other bishop.' } },
          { san: 'e3', explanation: { pt: 'Reforça o centro e prepara o desenvolvimento do bispo de casas claras.', en: 'Reinforces the center and prepares to develop the light-squared bishop.' } },
          { san: 'Bd6', explanation: { pt: 'Desenvolve o bispo, desafiando o bispo branco na mesma diagonal.', en: "Develops the bishop, challenging White's bishop on the same diagonal." } },
          { san: 'Bg3', explanation: { pt: 'Evita a troca de bispos, mantendo a peça ativa.', en: 'Avoids the bishop trade, keeping the piece active.' } },
        ],
      },
      {
        name: { pt: 'Contra a Defesa Eslava', en: 'Against the Slav Defense' },
        eco: 'D02',
        moves: [
          { san: 'd4', explanation: { pt: 'Ocupa o centro.', en: 'Occupies the center.' } },
          { san: 'd5', explanation: { pt: 'Resposta simétrica.', en: 'Symmetric response.' } },
          { san: 'Nf3', explanation: { pt: 'Desenvolve.', en: 'Develops.' } },
          { san: 'Nf6', explanation: { pt: 'Desenvolve simetricamente.', en: 'Develops symmetrically.' } },
          { san: 'Bf4', explanation: { pt: 'O Sistema Londres: desenvolve o bispo antes de lhe fechar a saída com e3.', en: 'The London System: develops the bishop before closing its escape route with e3.' } },
          { san: 'c6', explanation: { pt: 'Pretas respondem com uma estrutura tipo Eslava, reforçando d5 e preparando ...Bf5.', en: 'Black responds with a Slav-like structure, reinforcing d5 and preparing ...Bf5.' } },
          { san: 'e3', explanation: { pt: 'Reforça o centro.', en: 'Reinforces the center.' } },
          { san: 'Bf5', explanation: { pt: 'Desenvolve o próprio bispo de casas claras antes de o fechar, espelhando a ideia branca.', en: "Develops its own light-squared bishop before shutting it in, mirroring White's idea." } },
          { san: 'Bd3', explanation: { pt: 'Oferece a troca de bispos, disposto a simplificar para uma posição sólida e fácil de jogar.', en: 'Offers the bishop trade, willing to simplify into a solid, easy-to-play position.' } },
        ],
      },
    ],
  },
];
